### PR TITLE
fix import after refactoring processing plugin: should fix #10953

### PR DESCRIPTION
**Pull request by slarosa**

### CODE REVIEW

**Comment by luipir** [comment]
should be managed Processing version to be compatible with other installation.
I did modification but I was waiting the end of processing refactoring to commit a definitive fix
What do you think about?

**Comment by slarosa** [comment]
Hi,
I just added the check for QGIS version, I think it enough right now in order to have it working in >=2.5 and previous ones.

**Comment by slarosa** [comment]
Yes, we can wait for the complete refactoring, I noticed that parameters were not displayed in qgis dev version so I done the modification ;-) No problem to wait your commit :-)

**Comment by luipir** [comment]
the problem is if someone works on qgis master but he need sometimes Processing (master) and sometime install Processing legacy (due to model compatibility). I know some people that work in this way... simply uninstalling Processing plugin (from Plugin Manager)

**Comment by luipir** [comment]
checking my code this where my patch that mana processing refactoring

I didn't pushed because I was waiting the end of refactoring

try:
-    from processing.outputs.OutputVector import OutputVector
  +except:
-    from processing.core.outputs import OutputVector
  +try:
-    from processing.core.parameters import ParameterVector
  +except:
-    from processing.parameters.ParameterVector import ParameterVector

**Comment by luipir** [comment]
Hi I update to 0.4.4 with a "multi version" modification, let me know if this pull request is still necessary

**Comment by slarosa** [comment]
Thanks @luipir, if your solution works then this PR is not longer necessary.
I didn't try whether it is working with different version of processing plugin. I always used the one shipped with qgis dev version.
However, I did test the 0.4.4 in current master branch and I see the output parameter is not displayed, does it work fine for you?

**Comment by luipir** [comment]
do you refer to the "Output Layer" Line edit ? if so... In my case it works (qgis master 797cd47 and processing 2.4)

**Comment by slarosa** [comment]
Yes, I meant the output line edit, for me it is not working (I am in 86987b5 and processing 2.4)

**Comment by luipir** [comment]
Did you test a clean compilation?

**Comment by slarosa** [comment]
@luipir wrote:

> Did you test a clean compilation?

yes, with a clean compiled version now it is fine, thanks!

**Pull request closed without merging**
